// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: report.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	GrossIncome          float64                `protobuf:"fixed64,1,opt,name=gross_income,json=grossIncome,proto3" json:"gross_income,omitempty"`
	SicknessContribution bool                   `protobuf:"varint,2,opt,name=sickness_contribution,json=sicknessContribution,proto3" json:"sickness_contribution,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMessage) GetGrossIncome() float64 {
	if x != nil {
		return x.GrossIncome
	}
	return 0
}

func (x *RequestMessage) GetSicknessContribution() bool {
	if x != nil {
		return x.SicknessContribution
	}
	return false
}

type ContributionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Base          float64                `protobuf:"fixed64,3,opt,name=base,proto3" json:"base,omitempty"`
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContributionMessage) Reset() {
	*x = ContributionMessage{}
	mi := &file_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionMessage) ProtoMessage() {}

func (x *ContributionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionMessage.ProtoReflect.Descriptor instead.
func (*ContributionMessage) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

func (x *ContributionMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContributionMessage) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ContributionMessage) GetBase() float64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *ContributionMessage) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type ReportMessage struct {
	state                                           protoimpl.MessageState `protogen:"open.v1"`
	Name                                            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfWorkingHours                            int64                  `protobuf:"varint,2,opt,name=number_of_working_hours,json=numberOfWorkingHours,proto3" json:"number_of_working_hours,omitempty"`
	GrossPerHour                                    float64                `protobuf:"fixed64,3,opt,name=gross_per_hour,json=grossPerHour,proto3" json:"gross_per_hour,omitempty"`
	GrossIncome                                     float64                `protobuf:"fixed64,4,opt,name=gross_income,json=grossIncome,proto3" json:"gross_income,omitempty"`
	NetIncome                                       float64                `protobuf:"fixed64,5,opt,name=net_income,json=netIncome,proto3" json:"net_income,omitempty"`
	SicknessContribution                            bool                   `protobuf:"varint,6,opt,name=sickness_contribution,json=sicknessContribution,proto3" json:"sickness_contribution,omitempty"`
	BaseForCalculationOfContributionsPaidByCountry  float64                `protobuf:"fixed64,7,opt,name=base_for_calculation_of_contributions_paid_by_country,json=baseForCalculationOfContributionsPaidByCountry,proto3" json:"base_for_calculation_of_contributions_paid_by_country,omitempty"`
	BaseForCalculationOfContributionsPaidByEmployer float64                `protobuf:"fixed64,8,opt,name=base_for_calculation_of_contributions_paid_by_employer,json=baseForCalculationOfContributionsPaidByEmployer,proto3" json:"base_for_calculation_of_contributions_paid_by_employer,omitempty"`
	EmployerTotalCost                               float64                `protobuf:"fixed64,9,opt,name=employer_total_cost,json=employerTotalCost,proto3" json:"employer_total_cost,omitempty"`
	ContributionPaidByCountry                       []*ContributionMessage `protobuf:"bytes,10,rep,name=contribution_paid_by_country,json=contributionPaidByCountry,proto3" json:"contribution_paid_by_country,omitempty"`
	ContributionPaidByEmployee                      []*ContributionMessage `protobuf:"bytes,11,rep,name=contribution_paid_by_employee,json=contributionPaidByEmployee,proto3" json:"contribution_paid_by_employee,omitempty"`
	ContributionPaidByEmployer                      []*ContributionMessage `protobuf:"bytes,12,rep,name=contribution_paid_by_employer,json=contributionPaidByEmployer,proto3" json:"contribution_paid_by_employer,omitempty"`
	unknownFields                                   protoimpl.UnknownFields
	sizeCache                                       protoimpl.SizeCache
}

func (x *ReportMessage) Reset() {
	*x = ReportMessage{}
	mi := &file_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMessage) ProtoMessage() {}

func (x *ReportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMessage.ProtoReflect.Descriptor instead.
func (*ReportMessage) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{2}
}

func (x *ReportMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportMessage) GetNumberOfWorkingHours() int64 {
	if x != nil {
		return x.NumberOfWorkingHours
	}
	return 0
}

func (x *ReportMessage) GetGrossPerHour() float64 {
	if x != nil {
		return x.GrossPerHour
	}
	return 0
}

func (x *ReportMessage) GetGrossIncome() float64 {
	if x != nil {
		return x.GrossIncome
	}
	return 0
}

func (x *ReportMessage) GetNetIncome() float64 {
	if x != nil {
		return x.NetIncome
	}
	return 0
}

func (x *ReportMessage) GetSicknessContribution() bool {
	if x != nil {
		return x.SicknessContribution
	}
	return false
}

func (x *ReportMessage) GetBaseForCalculationOfContributionsPaidByCountry() float64 {
	if x != nil {
		return x.BaseForCalculationOfContributionsPaidByCountry
	}
	return 0
}

func (x *ReportMessage) GetBaseForCalculationOfContributionsPaidByEmployer() float64 {
	if x != nil {
		return x.BaseForCalculationOfContributionsPaidByEmployer
	}
	return 0
}

func (x *ReportMessage) GetEmployerTotalCost() float64 {
	if x != nil {
		return x.EmployerTotalCost
	}
	return 0
}

func (x *ReportMessage) GetContributionPaidByCountry() []*ContributionMessage {
	if x != nil {
		return x.ContributionPaidByCountry
	}
	return nil
}

func (x *ReportMessage) GetContributionPaidByEmployee() []*ContributionMessage {
	if x != nil {
		return x.ContributionPaidByEmployee
	}
	return nil
}

func (x *ReportMessage) GetContributionPaidByEmployer() []*ContributionMessage {
	if x != nil {
		return x.ContributionPaidByEmployer
	}
	return nil
}

var File_report_proto protoreflect.FileDescriptor

const file_report_proto_rawDesc = "" +
	"\n" +
	"\freport.proto\x12\areports\"h\n" +
	"\x0eRequestMessage\x12!\n" +
	"\fgross_income\x18\x01 \x01(\x01R\vgrossIncome\x123\n" +
	"\x15sickness_contribution\x18\x02 \x01(\bR\x14sicknessContribution\"s\n" +
	"\x13ContributionMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04base\x18\x03 \x01(\x01R\x04base\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\"\xa8\x06\n" +
	"\rReportMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\x17number_of_working_hours\x18\x02 \x01(\x03R\x14numberOfWorkingHours\x12$\n" +
	"\x0egross_per_hour\x18\x03 \x01(\x01R\fgrossPerHour\x12!\n" +
	"\fgross_income\x18\x04 \x01(\x01R\vgrossIncome\x12\x1d\n" +
	"\n" +
	"net_income\x18\x05 \x01(\x01R\tnetIncome\x123\n" +
	"\x15sickness_contribution\x18\x06 \x01(\bR\x14sicknessContribution\x12m\n" +
	"5base_for_calculation_of_contributions_paid_by_country\x18\a \x01(\x01R.baseForCalculationOfContributionsPaidByCountry\x12o\n" +
	"6base_for_calculation_of_contributions_paid_by_employer\x18\b \x01(\x01R/baseForCalculationOfContributionsPaidByEmployer\x12.\n" +
	"\x13employer_total_cost\x18\t \x01(\x01R\x11employerTotalCost\x12]\n" +
	"\x1ccontribution_paid_by_country\x18\n" +
	" \x03(\v2\x1c.reports.ContributionMessageR\x19contributionPaidByCountry\x12_\n" +
	"\x1dcontribution_paid_by_employee\x18\v \x03(\v2\x1c.reports.ContributionMessageR\x1acontributionPaidByEmployee\x12_\n" +
	"\x1dcontribution_paid_by_employer\x18\f \x03(\v2\x1c.reports.ContributionMessageR\x1acontributionPaidByEmployer2G\n" +
	"\aGreeter\x12<\n" +
	"\tGetReport\x12\x17.reports.RequestMessage\x1a\x16.reports.ReportMessageB\n" +
	"Z\b/reportsb\x06proto3"

var (
	file_report_proto_rawDescOnce sync.Once
	file_report_proto_rawDescData []byte
)

func file_report_proto_rawDescGZIP() []byte {
	file_report_proto_rawDescOnce.Do(func() {
		file_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)))
	})
	return file_report_proto_rawDescData
}

var file_report_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_report_proto_goTypes = []any{
	(*RequestMessage)(nil),      // 0: reports.RequestMessage
	(*ContributionMessage)(nil), // 1: reports.ContributionMessage
	(*ReportMessage)(nil),       // 2: reports.ReportMessage
}
var file_report_proto_depIdxs = []int32{
	1, // 0: reports.ReportMessage.contribution_paid_by_country:type_name -> reports.ContributionMessage
	1, // 1: reports.ReportMessage.contribution_paid_by_employee:type_name -> reports.ContributionMessage
	1, // 2: reports.ReportMessage.contribution_paid_by_employer:type_name -> reports.ContributionMessage
	0, // 3: reports.Greeter.GetReport:input_type -> reports.RequestMessage
	2, // 4: reports.Greeter.GetReport:output_type -> reports.ReportMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_report_proto_init() }
func file_report_proto_init() {
	if File_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_proto_goTypes,
		DependencyIndexes: file_report_proto_depIdxs,
		MessageInfos:      file_report_proto_msgTypes,
	}.Build()
	File_report_proto = out.File
	file_report_proto_goTypes = nil
	file_report_proto_depIdxs = nil
}
